#!/usr/bin/env bash
set -euo pipefail

mode="dry-run"
if [[ "${1:-}" == "--apply" ]]; then
  mode="apply"
  shift
elif [[ "${1:-}" == "--dry-run" ]]; then
  shift
fi

if (($# == 0)); then
  cat <<'USAGE'
Usage:
  scripts/retire-dotagents-state.sh [--dry-run|--apply] ROOT [...]

Retires legacy dotagents manifests that only point back to the skills already
stored in each ROOT. It never removes a skill directory or agent projection.
The default is a dry run. --apply requires the macOS `trash` command.

Pass ~/.agents for the global collection and repository roots for project
collections.
USAGE
  exit 2
fi

if [[ "$mode" == "apply" ]] && ! command -v trash >/dev/null 2>&1; then
  echo "trash is required for --apply" >&2
  exit 1
fi

declare -a roots=("$@")
validation_failed=0

validate_state_file() {
  local state_file="$1"
  local expected_prefix="$2"
  local line=""
  local current_name=""
  local current_source=""
  local in_skill=0
  local source_seen=0
  local source_readable=0
  local skill_block_count=0

  finish_skill_block() {
    if ((in_skill == 0)); then
      return 0
    fi
    if [[ -z "$current_name" ]]; then
      echo "refusing $state_file: skill block has no readable name" >&2
      validation_failed=1
    elif [[ ! "$current_name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
      echo "refusing $state_file: invalid skill name $current_name" >&2
      validation_failed=1
    elif ((source_seen == 0)); then
      echo "refusing $state_file: skill $current_name has no source" >&2
      validation_failed=1
    elif ((source_readable == 0)); then
      echo "refusing $state_file: skill $current_name has an unreadable source" >&2
      validation_failed=1
    elif [[ "$current_source" != "$expected_prefix$current_name" ]]; then
      echo "refusing $state_file: $current_name uses independent source $current_source" >&2
      validation_failed=1
    fi
  }

  while IFS= read -r raw_line; do
    line="${raw_line#"${raw_line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"

    if [[ "$line" =~ ^\[\[skills\]\]([[:space:]]*#.*)?$ ]]; then
      finish_skill_block
      current_name=""
      current_source=""
      in_skill=1
      source_seen=0
      source_readable=0
      skill_block_count=$((skill_block_count + 1))
      continue
    fi

    if [[ "$line" =~ ^\[skills\.([^\]]+)\]([[:space:]]*#.*)?$ ]]; then
      finish_skill_block
      current_name="${BASH_REMATCH[1]}"
      current_name="${current_name//\"/}"
      current_name="${current_name//\'/}"
      current_source=""
      in_skill=1
      source_seen=0
      source_readable=0
      skill_block_count=$((skill_block_count + 1))
      continue
    fi

    if [[ "$line" == \[* ]]; then
      finish_skill_block
      current_name=""
      current_source=""
      in_skill=0
      source_seen=0
      source_readable=0
      continue
    fi

    if ((in_skill == 0)); then
      continue
    fi

    if [[ "$line" =~ ^name[[:space:]]*=[[:space:]]*[\"\']([^\"\']+)[\"\'] ]]; then
      current_name="${BASH_REMATCH[1]}"
      continue
    fi

    if [[ "$line" =~ ^source[[:space:]]*=[[:space:]]*[\"\']([^\"\']+)[\"\'] ]]; then
      current_source="${BASH_REMATCH[1]}"
      source_seen=1
      source_readable=1
    elif [[ "$line" =~ ^source[[:space:]]*= ]]; then
      source_seen=1
      source_readable=0
    fi
  done < "$state_file"

  finish_skill_block
  if ((skill_block_count == 0)); then
    echo "refusing $state_file: no skill declarations were found" >&2
    validation_failed=1
  fi
}

for root in "${roots[@]}"; do
  root="${root%/}"
  if [[ ! -d "$root" ]]; then
    echo "missing root: $root" >&2
    validation_failed=1
    continue
  fi

  if [[ "$(basename "$root")" == ".agents" ]]; then
    expected_prefix="path:skills/"
  else
    expected_prefix="path:.agents/skills/"
  fi

  for state_file in "$root/agents.toml" "$root/agents.lock"; do
    [[ -f "$state_file" ]] || continue
    validate_state_file "$state_file" "$expected_prefix"
  done
done

if ((validation_failed != 0)); then
  echo "No files changed." >&2
  exit 1
fi

for root in "${roots[@]}"; do
  root="${root%/}"
  for state_file in "$root/agents.toml" "$root/agents.lock"; do
    [[ -f "$state_file" ]] || continue
    if [[ "$mode" == "apply" ]]; then
      trash "$state_file"
      echo "trashed: $state_file"
    else
      echo "would trash: $state_file"
    fi
  done

  if [[ "$(basename "$root")" == ".agents" ]]; then
    generated_ignore="$root/.gitignore"
  else
    generated_ignore="$root/.agents/.gitignore"
  fi
  if [[ -f "$generated_ignore" ]] \
    && head -n 1 "$generated_ignore" | grep -q '^# Auto-generated by dotagents'; then
    payload="$(grep -Ev '^[[:space:]]*(#.*)?$' "$generated_ignore" || true)"
    if [[ -z "$payload" ]]; then
      if [[ "$mode" == "apply" ]]; then
        trash "$generated_ignore"
        echo "trashed empty generated ignore: $generated_ignore"
      else
        echo "would trash empty generated ignore: $generated_ignore"
      fi
    else
      echo "preserving non-empty generated ignore for manual provenance review: $generated_ignore"
    fi
  fi
done

echo "Skills and projection paths were not modified."
